#! /usr/bin/env python

import argparse

from colabcode import ColabCode


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="ColabCode: Run VS Code On Colab / Kaggle Notebooks"
    )
    parser._action_groups.pop()
    required = parser.add_argument_group("required arguments")
    optional = parser.add_argument_group("optional arguments")

    required.add_argument(
        "--port",
        type=int,
        help="the port you want to run code-server on",
        required=True,
    )
    optional.add_argument(
        "--password",
        type=str,
        help="password to protect your code-server from unauthorized access",
        default=None,
    )
    optional.add_argument(
        "--mount_drive",
        action="store_true",
        help="if you use --mount_drive, your google drive will be mounted",
    )
    optional.add_argument(
        "--user_data_dir",
        type=str,
        help="Custom folder path for storing user related data",
        default=None,
    )
    optional.add_argument(
        "--extensions_dir",
        type=str,
        help="Custom folder path for storing installed extentions",
        default=None,
    )
    optional.add_argument(
        "--config",
        type=str,
        help="Custom file path for code-server config file",
        default=None,
    )

    args = parser.parse_args()

    ColabCode(
        port=args.port,
        password=args.password,
        mount_drive=args.mount_drive,
        user_data_dir=args.user_data_dir,
        extensions_dir=args.extensions_dir,
        config=args.config,
    )
